### ISSUE TITLE
gRPC INFO Logs Appearing as ERROR in Google Cloud Logs

### ISSUE THREAD

**Issue by ArunkumarrNatarajan** [world-federation-of-advertisers/cross-media-measurement#2093]
**Describe the bug**
We have observed that gRPC calls logged at the **INFO** level are incorrectly displayed with **ERROR** severity in Google Cloud Logs. However, the actual log content indicates that the messages are at the **INFO** level.

**Steps to reproduce**
1. Submit a report on the Origin applicaiton. 
2. Check the log entry in the Kingdom Google Cloud account .
3.  Observe that the severity is incorrectly marked as ERROR instead of INFO.

**Component(s) affected**
Kingdom, Duchy, Reporting Server

**Version**
0.5.15
**Environment**
Origin PROD

![Image](https://github.com/user-attachments/assets/d8458fd7-d71e-45f5-8b9d-00198134bec8)

**Comment by SanjayVas** [comment]
I've taken the liberty of updating the original filing to specify this was found in Origin's PROD environment (as opposed to another market).

This is not observed in any Halo test environment. If you're observing this, it's most likely because of a configuration error. Ensure the following in your configuration:

1.  Ensure you have the Java logging config file available in a mount. In the default configuration, this is in a ConfigMap called `java`:

    ```yaml
    apiVersion: v1
    data:
      logging.properties: |-
        .level = INFO
    
        io.grpc.netty.level=INFO
        sun.net.level=INFO
    
        handlers = java.util.logging.ConsoleHandler
        java.util.logging.ConsoleHandler.level = INFO
        java.util.logging.ConsoleHandler.formatter = org.wfanet.measurement.gcloud.logging.StructuredLoggingFormatter
    kind: ConfigMap
    metadata:
      labels:
        app.kubernetes.io/name: java
        app.kubernetes.io/part-of: halo-cmms
      name: java
    ```

  This is specified in the K8s config for the Deployment as the following Volume and VolumeMount:

  ```yaml
  - configMap:
      defaultMode: 420
      name: java
    name: java-config
  ```

  ```yaml
  - mountPath: /etc/java
    name: java-config
    readOnly: true
  ```

2.  The `java.util.logging.config.file` system property is specified in your JAVA_TOOL_OPTIONS environment variable. For example, this is the relevant section in the YAML K8s config for the Kingdom public API server for Halo test environments:   
    ```yaml
    env:
    - name: JAVA_TOOL_OPTIONS
      value: -Xmx64M -Xms64M -Dio.netty.maxDirectMemory=0 -Djdk.nio.maxCachedBufferSize=262144
        -Djava.util.logging.config.file=/etc/java/logging.properties -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/run/heap-dumps -XX:+ExitOnOutOfMemoryError
    ```
